// Generated by https://quicktype.io

export interface University {
    _id:          string;
    country:      string;
    website:      string;
    types:        string[];
    last_updated: string;
    ranks:        Ranks;
    names:        Names;
    synonyms:     Synonyms;
    name:         string;
    id:           string;
    source:       string;
}

export interface Names {
    vi: string;
    en: string;
}

export interface Ranks {
    the:  number;
    qs:   number;
    arwu: number;
}

export interface Synonyms {
    de: De[];
    vi: De[];
    en: string[];
    fr: De[];
}

export interface De {
}
