name: client
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build